### ISSUE TITLE
Unable to import tflite package

### ISSUE THREAD

**Issue by mrcartier** [shaqian/flutter_tflite#1]
Good work, we need this for Flutter. I'm referencing the [example here](https://github.com/shaqian/flutter_tflite/tree/master/example) where the file under the lib folder is main.dart not tflite.dart. I'm having issue importing tflite package though. IntelliJ tells me: Target of URI doesn't exist: 'package:tflite/tflite.dart'. for the line

    import 'package:tflite/tflite.dart';

I believe I've added tflite package properly to the pubscec.yaml file using [instructions here](https://pub.dartlang.org/packages/tflite#-installing-tab-) but it still won't work...

    dev_dependencies:
      flutter_test:
        sdk: flutter

      image_picker: ^0.4.10
      tflite: ^0.0.2

any ideas why I can't import

**Comment by shaqian** [comment]
Hi mrcartier,

I tested with Android Studio and vscode and importing seems to be working. 

Do you see an entry like below in the `.flutter-plugin` file? It points to the directory where the plugin lib files are stored.
`tflite=/Users/sha/flutter/.pub-cache/hosted/pub.dartlang.org/tflite-0.0.2/`

Thanks,
Qian

**Comment by mrcartier** [comment]
It was my fault. I named the project folder tflite and you can't name the project folder after a dependency. Thanks for feedback & getting tflow on Flutter.
