### ISSUE TITLE
where can I enable GPU delegates?

### ISSUE THREAD

**Issue by jeffersondarcy** [shaqian/flutter_tflite#106]
I am not sure whether the gpu delegates are enabled - can somebody tell me how to enable them when not?

**Comment by AbdulRashidReshamwala** [comment]
Looked at the source code there is currently no way to add gpu delegates i will try to for and add support for the android part @shaqian can somebody do the same for ios

**Comment by jeffersondarcy** [comment]
thx

**Comment by remcova** [comment]
@AbdulRashidReshamwala any news on this?

**Comment by AbdulRashidReshamwala** [comment]
sent a pull request for android version https://github.com/shaqian/flutter_tflite/pull/124 @jeffersondarcy  @remcova

**Comment by remcova** [comment]
> sent a pull request for android version #124 @jeffersondarcy @remcova

Thank you

**Comment by shaqian** [comment]
It's now supported in latest version 1.1.0. Set `useGpuDelegate` to `true` in `loadModel`. 

Thanks,
Qian
