### ISSUE TITLE
Object Detection?

### ISSUE THREAD

**Issue by dkashkin** [shaqian/flutter_tflite#11]
Hello! I like this plugin but it seems to be limited to Image Classification while TFLite also supports Object Detection models. Do you have any plans for incorporating object detection into this plugin?

**Comment by shaqian** [comment]
Hello!
Are you referring to something like below? 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/TFLiteObjectDetectionAPIModel.java
I haven't tried the ssd mobilenet model but will see if I can incorporate it.

**Comment by dkashkin** [comment]
Yes, this is the only example of using TFLite for object detection that I was able to find. I wish they had an iOS version of that... Anyways, my hope is that both Image Classification and Object Detection models use the same exact TFLite API, so with some luck your plugin flutter_tflite should be able to support object detection with minimum code changes...

**Comment by shaqian** [comment]
Hi,
I added object detection in v1.0.0. Supports SSD MobileNet and Tiny YOLOv2.
https://github.com/shaqian/flutter_tflite#object-detection 
The sample app is updated too.
https://github.com/shaqian/flutter_tflite/tree/master/example

**Comment by shaqian** [comment]
Archiving the thread.
