### ISSUE TITLE
Failed to mmap model in example app

### ISSUE THREAD

**Issue by NoraKrbr** [shaqian/flutter_tflite#13]
Hello!
I tried to get your example app to work. When I click on the button Tiny YOLOv2, I always get the error message:

flutter: Failed to mmap model /var/containers/Bundle/Application/F91D7024-D937-4D94-BDC2-5CC6C8A273E8/Runner.app/Frameworks/App.framework/flutter_assets/assets/yolov2_tiny.tflite

It's the same for the other two models. 

I have created the assets folder and also included the assets in my pubspec.yaml:
assets:
     - assets/mobilenet_v1_1.0_224.tflite
     - assets/mobilenet_v1_1.0_224.txt
     - assets/ssd_mobilenet.tflite
     - assets/ssd_mobilenet.txt
     - assets/yolov2_tiny.tflite
     - assets/yolov2_tiny.txt

Could you give me an idea on what it is not working correctly?

**Comment by shaqian** [comment]
Hello,

Can you please try to launch the app from Xcode? Do you get more trace?

Thanks,
Qian

**Comment by NoraKrbr** [comment]
Hi Qian,

thanks for you reply!
In the meantime I deleted the old project and tried to set everything up step by step again. I now have a different error, when trying to build the app:

Xcode's output:
↳
    === BUILD TARGET image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Volumes/Transcend/Studium/Bachelorarbeit/dev/flutter/.pub-cache/hosted/pub.dartlang.org/tflite-1.0.1/ios/Classes/TflitePlugin.mm:11:10: fatal error: 'tensorflow/contrib/lite/kernels/register.h' file not found
    #include "tensorflow/contrib/lite/kernels/register.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

When I look at my directories it seems that 'lite' is not in the contrib folder of tensorflow but on the same level. This tensorflow folder is in my flutter directory, but should it be in the project folder?

Sorry if my questions are unclear, I am still very new to flutter development and to asking questions to the community as well :)

Thanks,
Nora

**Comment by shaqian** [comment]
Hi Nora,

You can add the header path manually. Open Runner.xcworkspace in Xcode, go to Pods > Targets > tflite > Build Settings > User Header Search Path and add the path. 

Thanks,
Qian

**Comment by FredrikBakken** [comment]
I experienced the same issues as @NoraKrbr for my iOS build. A local fix to the issue could be to go to `ios/.symlinks/plugins/tflite/ios/Classes/TflitePlugin.mm` and change the #include paths to:
```
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/string_util.h"
#include "tensorflow/lite/op_resolver.h"
```

I have also created a pull-request for this feature here: https://github.com/shaqian/flutter_tflite/pull/17.

**Comment by NoraKrbr** [comment]
Thank you for the answers!
When I change the code as @FredrikBakken suggested, I don't have buildtime issues anymore. But now this error that I had before is there again:

Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 8QXZP8UMC6
Running Xcode build...
Xcode build done.                                           61,2s
Installing and launching...
Syncing files to device iPhone...
flutter: Failed to mmap model /var/containers/Bundle/Application/6800033C-F69B-4B63-8700-E67FDEA5C89A/Runner.app/Frameworks/App.framework/flutter_assets/assets/ssd_mobilenet.tflite

Does anyone know what could be the problem?

**Comment by shaqian** [comment]
I think the error is from the following method.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/model.cc#L166-L175

Basically it's checking if the first 4 characters of the model file is "TFL3" but in your case it's '<!'.

Can you please run the following command to check what's in your model file? Maybe the file is incomplete?
sed -n '1p' ssd_mobilenet.tflite 
TFL3
   ???
?????>??>??>??>??>??>??>p?>`?>P?>@?>??> ?>P?>?>p?>`?>P?>@(<8(<(?9?.?M.?A.?&.h&.X?)H?)8?)(Z'?XW'?%??"X?"H?!x?!h!?

**Comment by jithin-pal** [comment]
I have built a custom ML model when it comes to a prediction it is crashing the application. What is the error? When I use the mobile net downloaded from internet works fine. How do I fix this?

**Comment by oezguensi** [comment]
Actually completely stopping the app (instead of restarting) and re-running worked for me.
