### ISSUE TITLE
Failed to load up the app

### ISSUE THREAD

**Issue by john-law** [shaqian/flutter_tflite#14]
App does not load up. It gets installed but does not open. On the terminal it hangs on the step after installing the apk. I've seen that other people are able to run it so I'm guessing it's something specific to me. Has anyone faced a similar problem?

**Steps to reproduce:**
- Clone repo
- cd to example
- `flutter packages get`
- `flutter run`

**Device:**
- Redmi 6A

**OS**
- Android 8.1.0

**Tried and did not work:**
- Uninstalling the app via `adb uninstall ${package_name}`, and doing `flutter run` again

**Comment by shaqian** [comment]
Hi John,

Can you try to open the `Android` folder in Android Studio and launch app in Debug mode?

Thanks,
Qian
