### ISSUE TITLE
how can i use another deep learning technic?

### ISSUE THREAD

**Issue by zmqp111** [shaqian/flutter_tflite#15]
Hi guys.

I'm making an app using the flutter.
I'd like to experiment with a variety of deep learning algorithms using the flutter tf-lite, do you know how?
(for example, image segmentation, landmark detection, etc..)

If there is any method or related material, please let me know.

Thanks, Regard.

**Comment by shaqian** [comment]
Hi,

You will need to implement them in the native code and bridge the native code with Flutter. 

For example, for image segmentation using deeplab, you can refer to this RP in the tensorflow repo.  
https://github.com/tensorflow/tensorflow/pull/25785

I will try to add them to this library too when I have time. 

Thanks,
Qian

**Comment by shaqian** [comment]
Archiving the thread as deeplab support is added in v1.0.3.

Thanks,
Qian
