### ISSUE TITLE
runModelOnImage to get lower results

### ISSUE THREAD

**Issue by ngptruong** [shaqian/flutter_tflite#153]
Is It possible to get the results of all the predictions according to classes?
For example:
{
  index: 0,
  label: "person",
  confidence: 0.89
},
{
  index: 1
  label: "cat",
  confidence: 0.22
},
...

**Comment by Alfyu07** [comment]
Did you get the answer? because i have the same problems

**Comment by ngptruong** [comment]
```
  classifyImagetest(File image) async {
    var outputs = await Tflite.runModelOnImage(
     path: image.path,
     numResults: 6,
     threshold: 0,
     imageMean: 127.5,
     imageStd: 127.5,
    );
    setState(() {
      _loading = false;
      _outputs = outputs;
      result1 = _outputs[1]["label"];
      result2 = _outputs[2]["label"];
    });
```

Try this, result1, and result2 may be the second and third prediction.
