### ISSUE TITLE
Can you please add opportunity to use "MobileNet" model with more labels

### ISSUE THREAD

**Issue by Renesanse** [shaqian/flutter_tflite#16]
```private List<Map<String, Object>> detectObjectOnBinary(HashMap args) throws IOException {
byte[] binary = (byte[])args.get("binary");
String model = args.get("model").toString();
double threshold = (double)args.get("threshold");
float THRESHOLD = (float)threshold;
List ANCHORS = (ArrayList)args.get("anchors");
int BLOCK_SIZE = (int)args.get("blockSize");
int NUM_BOXES_PER_BLOCK = (int)args.get("numBoxesPerBlock");
int NUM_RESULTS_PER_CLASS = (int)args.get("numResultsPerClass");

ByteBuffer imgData = ByteBuffer.wrap(binary);

if (model.equals("SSDMobileNet")) {
  return parseSSDMobileNet(imgData, NUM_RESULTS_PER_CLASS, THRESHOLD);
} else {
  return parseYOLO(imgData, BLOCK_SIZE, NUM_BOXES_PER_BLOCK, ANCHORS, THRESHOLD, NUM_RESULTS_PER_CLASS);
}
}
```
sorry, no link, old browser

**Comment by shaqian** [comment]
Hi Daniel,

What do you mean by using more labels? The library reads labels from the asset file you assigned to loadModel() method.

Thanks,
Qian

**Comment by Renesanse** [comment]
Well, I tried to use just a MobileNet model and found a problem, wrong dimensions compared with the java array. To see a problem, try to load "MobileNet" model with txt which follows

**Comment by westracer** [comment]
@Renesanse Do you mean another number of detections? Because when I tried to use retrained model I got error like [1,10,4] isn't [1,16,4]. After changing that const, everything went well, though I have different labels.

**Comment by Renesanse** [comment]
> @Renesanse Do you mean another number of detections? Because when I tried to use retrained model I got error like [1,10,4] isn't [1,16,4]. After changing that const, everything went well, though I have different labels.
 can you show me please, where I should change consts to use MobileNet model, not a SSDMobileNet. It is not clear for me now.

**Comment by shaqian** [comment]
MobileNet is image classification model. Instead of detectObjectOnImage method, please use runModelOnImage. 
https://github.com/shaqian/flutter_tflite#image-classification

**Comment by Renesanse** [comment]
ok, thx
