### ISSUE TITLE
Please add null safety

### ISSUE THREAD

**Issue by Abin-Thankachan** [shaqian/flutter_tflite#198]

**Comment by ben-xD** [comment]
@shaqian Is this a difficult challenge? I would be interested to try to do it :)

**Comment by shaqian** [comment]
Hi, I received this PR and it's been merged to v1.1.2: https://github.com/shaqian/flutter_tflite/pull/196

Thanks,
Qian

**Comment by zxenonx** [comment]
> Hi, I received this PR and it's been merged to v1.1.2: #196
> 
> Thanks,
> Qian

So the issue is resolved. It can be closed.
