### ISSUE TITLE
I got an error after the image selection was completed.

### ISSUE THREAD

**Issue by gaojuanjuan** [shaqian/flutter_tflite#21]
![image](https://user-images.githubusercontent.com/14133759/54795609-e3f08f00-4c87-11e9-82e2-c3dcffcd4615.png)

**Comment by shaqian** [comment]
Hi,
The error complains Interpreter is a null object reference. Do you get any errors when loading the model? You can set a breakpoint at this line:
https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L164

**Comment by hunnble** [comment]
make sure that you've loaded the model before you use it @gaojuanjuan 
see 'loadModel' in the example: https://github.com/shaqian/flutter_tflite/blob/master/example/lib/main.dart

**Comment by shaqian** [comment]
Archiving the thread. Feel free to reopen if you still have the issue. 

Thanks,
Qian
