### ISSUE TITLE
The plugin `tflite` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by rajkamal06** [shaqian/flutter_tflite#220]
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android
V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated
APIs.

**Comment by Tisanthan** [comment]
same issue

**Comment by erikbg7** [comment]
It is only considered a failure in newer versions of Flutter, V1 embedding is still allowed in Flutter v2.2.3. 
Download an older version of Flutter or try:
`flutter downgrade v2.2.3`
Hope it works!

**Comment by Amira-Ezz-149** [comment]
you can add 

```
aaptOptions {
        noCompress 'tflite'
        noCompress 'lite'
    }
```

after 
```
sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
```
in app/build.gradle
