### ISSUE TITLE
PlatformException : Failed to load model

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [shaqian/flutter_tflite#246]
Hello , i stuck in this confused issue that say in android :
```
 PlatformException(Failed to load model, assets/model.tflite (No such file or directory), java.io.FileNotFoundException: assets/model.tflite (No such file or directory)
```
im follow document and use https://teachablemachine.withgoogle.com/train/image to export tf model . and https://flutterawesome.com/face-mask-detection-with-tensorflow-flutter/ to following

**Comment by 2k16daniel** [comment]
check your yaml file then path for your model.tflite , maybe there's a typo in your filename or whut, take a look of my yaml here https://textbin.net/hymdqjqtxd
