### ISSUE TITLE
App closes when ever an Image is selected from Gallery 

### ISSUE THREAD

**Issue by Vasudev-2308** [shaqian/flutter_tflite#248]
I'm using Mobinet_Quant.tflite ( Renamed the Model though) to classify the image and to test out a few examples on my flutter applications. But whenever I try to select an image from the gallery, the application closes and exits the debugging session. 

I[/etection_tflit]()(  746): ProcessProfilingInfo new_methods=1025 is saved saved_to_disk=1 resolve_classes_delay=5000
I[/tflite]()  (  746): Initialized TensorFlow Lite runtime.
2
V[/PhoneWindow]()(  746): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@f1d2bfb, this = DecorView@1f46418[MainActivity]
V[/OplusZoomWindowDecorViewHelper]()(  746): setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.DecorView@1f46418[MainActivity]
E[/libEGL]()  (  746): Invalid file path for libcolorx-loader.so
I[/GED]()     (  746): [GT]_get_procNameprocess pid(746)
I[/GED]()     (  746): [GT]_getprocess name(com.example.object_detection_tflite)
I[/etection_tflit]()(  746): [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
2
E[/libEGL]()  (  746): Invalid file path for libcolorx-loader.so
I[/chatty]()  (  746): uid=10715(com.example.object_detection_tflite) RenderThread identical 5 lines
3
E[/libEGL]()  (  746): Invalid file path for libcolorx-loader.so
I[/chatty]()  (  746): uid=10715(com.example.object_detection_tflite) RenderThread identical 8 lines
4
E[/libEGL]()  (  746): Invalid file path for libcolorx-loader.so
I[/chatty]()  (  746): uid=10715(com.example.object_detection_tflite) RenderThread identical 15 lines
4
E[/libEGL]()  (  746): Invalid file path for libcolorx-loader.so
I[/chatty]()  (  746): uid=10715(com.example.object_detection_tflite) RenderThread identical 9 lines
2
E[/libEGL]()  (  746): Invalid file path for libcolorx-loader.so
I[/chatty]()  (  746): uid=10715(com.example.object_detection_tflite) RenderThread identical 11 lines
3
E[/libEGL]()  (  746): Invalid file path for libcolorx-loader.so
I[/chatty]()  (  746): uid=10715(com.example.object_detection_tflite) 1.raster identical 54 lines
E[/libEGL]()  (  746): Invalid file path for libcolorx-loader.so
I[/OplusFeatureCache]()(  746): Milliseconds spent on init(): 10
E[/ion]()     (  746): ioctl c0044901 failed with code -1: Invalid argument
Lost connection to device.
Exited (sigterm)`
`

**Comment by Eslam0mansour** [comment]
me too are u get answer?

**Comment by Vasudev-2308** [comment]
Nope Not yet. But I chose to do the task an alternative way where i click the picture and send it to a flask server. I have my trained model weights i.e. (.h5) file and then it processes and returns me an answer.
