### ISSUE TITLE
The plugin `tflite` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by efraindrummer** [shaqian/flutter_tflite#270]
Hola intente volver a una version de flutter, exactamente la version 2.2.3 ''' flutter downgrade v2.2.3 ''' pero ya no esta disponible, que solución hay para usar el paquete

**Comment by St-Luciferr** [comment]
you can use my fork I've included the changes in pull request "migrate support to android v2 embedding"
add this to your flutter dependencies
tflite:
    git:
      url: https://github.com/St-Luciferr/flutter_tflite.git

**Comment by efraindrummer** [comment]
Thank you very much for answering, I just tested the package and it works totally
