### ISSUE TITLE
My result list is empty.

### ISSUE THREAD

**Issue by adar2378** [shaqian/flutter_tflite#30]
Inference took 1183
I/flutter (32429): []
I/flutter (32429): []
this is what i get after executing 
final val = await Tflite.runModelOnImage(
        path: "/storage/emulated/0/Download/download.jpeg", // required
        imageMean: 0.0, // defaults to 117.0
        imageStd: 255.0, // defaults to 1.0
        numResults: 2, // defaults to 5
        threshold: 0.2, // defaults to 0.1
        asynch: true);
    print(val.toString());

**Comment by shaqian** [comment]
Hi Adar,
Are you using a model in this repo or your own? Can you try the example app?
https://github.com/shaqian/flutter_tflite/tree/master/example
Thanks,
Qian

**Comment by adar2378** [comment]
I've found the problem i think. My tflite file is not working actually. i've tried with other tflite file and it was working. Can you please tell me the proper way to convert a .pb file to tflite file? I've followed the tensorflow for poets tutorial. And used the inception_v3 model to retrain data. But I don't know how to convert that .pb file to tflite file properly. I've converted it somehow using toco but i guess it is not working properly :(

**Comment by shaqian** [comment]
Have you tried the command line tool tflite_convert?
https://www.tensorflow.org/lite/convert/cmdline_examples

**Comment by shaqian** [comment]
Temporarily archiving the thread. Feel free to reopen if you still have the issue.
