### ISSUE TITLE
Flutter TensorFlow Post estimation

### ISSUE THREAD

**Issue by RakhimyanTim** [shaqian/flutter_tflite#31]
Hi,

I need to use pose estimation model from [tensorflow](https://www.tensorflow.org/lite/models/pose_estimation/overview) in flutter. Can you explain how I can do it? 

Thank you!

**Comment by shaqian** [comment]
Hi Rakhimyan,

The pose estimation model in the link is implemented in JavaScript for TensorFlow.js. I don't think it's compatible with flutter. If you find any example in Android/iOS native code, I can try to integrate it to this plugin. 

Thanks,
Qian

**Comment by RakhimyanTim** [comment]
I see. Sure> Thanks!

**Comment by marcusfelix** [comment]
I have found posenet converted to .tflite ([multi_person_mobilenet_v1_075_float.tflite](https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/multi_person_mobilenet_v1_075_float.tflite)) but i think it is not compatible with this package.

**Comment by shaqian** [comment]
I see. I will take a look at the Android and iOS example. Will update this thread if I have any progress.

Thanks,
Qian

**Comment by shaqian** [comment]
PoseNet is now supported in v1.0.4. I also wrote a post about how it's implemented. 
https://medium.com/flutter-community/posenet-for-ios-android-and-flutter-using-tensorflow-lite-836788a110c7

Thanks,
Qian

**Comment by shaqian** [comment]
Archiving the thread as it's now supported.

**Comment by zeornelas** [comment]
Hi @shaqian ,

I'm having some trouble running your example. In order to become able to run it I had to upgrade the camera dependency, I'm using this dependencies:
``` 
camera: 0.5.7+2
tflite: 1.0.4
```
Whenever I run the posenet model I receive an empty array of recognitions.

What can I do to fix this?

Thanks,
zeo
