### ISSUE TITLE
get model from server,except assets!

### ISSUE THREAD

**Issue by liyoung1992** [shaqian/flutter_tflite#32]

**Comment by liyoung1992** [comment]
hello,
I  have many models(tflite),and it is work  when i  move .tflite to assets folder.but  if download from server,and save locally. after that  load tflite to app, it is not work.Do you support such operation?
thanks.

**Comment by shaqian** [comment]
Hi Liyoung,

At the moment the plugin doesn't support remote or non-asset files. 

One of the forks added the functionality to load local file but it was forked from an early version and I haven't tested it. 
https://github.com/sosospicy/flutter_tflite/commit/12fbbbc4a419d62271dc4d608ac3c7a98e2811e6

Thanks,
Qian

**Comment by liyoung1992** [comment]
Hi Qian,
Thank you very much,I did a test, it is work!

**Comment by shaqian** [comment]
Glad to know it works. :) 

I will go ahead and archive the thread. Feel free to raise a new issue if you have other questions.

Thanks,
Qian
