### ISSUE TITLE
There is always one more label than is in my model text.

### ISSUE THREAD

**Issue by raymondr** [shaqian/flutter_tflite#36]

**Comment by raymondr** [comment]
I was going to push a new branch and create a pull request but I don't seem to be allow to do this.
Here is the diff.
diff --git a/ios/Classes/TflitePlugin.mm b/ios/Classes/TflitePlugin.mm
index c73258e..6df78a1 100644
--- a/ios/Classes/TflitePlugin.mm
+++ b/ios/Classes/TflitePlugin.mm
@@ -121,9 +121,7 @@ static void LoadLabels(NSString* labels_path,
   }
   std::ifstream t;
   t.open([labels_path UTF8String]);
-  std::string line;
-  while (t) {
-    std::getline(t, line);
+  for (std::string line; std::getline(t, line); ) {
     label_strings->push_back(line);
   }
   t.close();

**Comment by raymondr** [comment]
#38 is the pull request to address this.

**Comment by shaqian** [comment]
Closing as the PR is merged.
