### ISSUE TITLE
Wont compile on dev channel

### ISSUE THREAD

**Issue by joeblew99** [shaqian/flutter_tflite#45]
Looks like a reference to the breaking API change with flutter 1.7  !!

````

cd /Users/apple/workspace/go/src/github.com/shaqian/flutter_tflite/example && flutter run -d all
No devices found
make: *** [mob-run] Error 1
x-MacBook-Pro:shaqian apple$ make mob-run
cd /Users/apple/workspace/go/src/github.com/shaqian/flutter_tflite/example && flutter run -d all
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...                                              3.3s
Resolving dependencies...                                           4.8s
                                                                        
Compiler message:                                                       
lib/app.dart:73:22: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/apple/fvm/master/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/apple/fvm/master/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
        .addListener((ImageInfo info, bool _) {                         
                     ^                                                  
Compiler failed on /Users/apple/workspace/go/src/github.com/shaqian/flutter_tflite/example/lib/main.dart
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/apple/fvm/master/packages/flutter_tools/gradle/flutter.gradle' line: 652
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileflutterBuildDebugArm64'.         
> Process 'command '/Users/apple/fvm/master/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 15s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        16.1s
Gradle task assembleDebug failed with exit code 1
make: *** [mob-run] Error 1

````

````
x-MacBook-Pro:shaqian apple$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.8.0, on Mac OS X 10.14.5 18F132, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)
````

**Comment by tnup** [comment]
import 'package:flutter/painting.dart';

And then change the 'new fileimage'function to

```
new FileImage(image).resolve(new ImageConfiguration()).addListener(
            new ImageStreamListener((ImageInfo info, bool synchronousCall) {
          setState(() {
            _imageHeight = info.image.height.toDouble();
            _imageWidth = info.image.width.toDouble();
          });
        }) as ImageStreamListener);

```
seems to solve this one.

**Comment by shaqian** [comment]
Yes. Looks like they changed `addListener` interface in painting library. 
https://github.com/flutter/flutter/commit/592f81e7c4eb31327b3cbf1e73d547587d6f7dea#diff-c40603317cbbb567a0ac6c32803d6788R292

Casting the type to `ImageStreamListener` as @tnup suggested should be the solution. 

Thanks,
Qian

**Comment by PrinceP** [comment]
I am receiving the following error. 
Exception has occurred.
_CastError (type '(ImageInfo, bool) => Null' is not a subtype of type 'ImageStreamListener' in type cast)


Launching lib/main.dart on Pixel 2 XL in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/tflite  ( 7567): Initialized TensorFlow Lite runtime.
I/flutter ( 7567): success
W/System  ( 7567): A resource failed to call close.
V/time    ( 7567): Inference took 233
I/flutter ( 7567): [{score: 0.9141436219215393, keypoints: {0: {score: 0.9366106390953064, part: nose, x: 0.9072170257568359, y: 0.7681019902229309}, 1: {score: 0.8853325247764587, part: leftEye, x: 0.9083921909332275, y: 0.7660269737243652}, 2: {score: 0.895061194896698, part: rightEye, x: 0.9051240086555481, y: 0.7632570266723633}, 3: {score: 0.6452447772026062, part: leftEar, x: 0.9123005270957947, y: 0.7663577198982239}, 4: {score: 0.5991162061691284, part: rightEar, x: 0.9066846966743469, y: 0.7621657252311707}, 5: {score: 0.9771823287010193, part: leftShoulder, x: 0.905788004398346, y: 0.7937831878662109}, 6: {score: 0.9885516166687012, part: rightShoulder, x: 0.901046633720398, y: 0.7925692796707153}, 7: {score: 0.9520376920700073, part: leftElbow, x: 0.9105158448219299, y: 0.8237140774726868}, 8: {score: 0.9721059203147888, part: rightElbow, x: 0.904983639717102, y: 0.8216578364372253}, 9: {score: 0.9290830492973328, part: leftWrist, x: 0.9192070960998535, y: 0.8451672196388245}, 10: {score: 0.9260290265083313, part: r

**Comment by tnup** [comment]
try this @PrinceP 

new FileImage(image)
    .resolve(new ImageConfiguration())
    .addListener( **new ImageStreamListener**((ImageInfo info, bool synchronousCall) {
          setState(() {
            _imageHeight = info.image.height.toDouble();
            _imageWidth = info.image.width.toDouble();
          });
        }) as ImageStreamListener);

    setState(() {
      _image = image;
      _busy = false;
    });
  }

double cast, but works.

**Comment by PrinceP** [comment]
@tnup Couldn't understand but this works. Thanks

**Comment by shaqian** [comment]
I'm archiving this thread. Feel free to reopen if you have further questions.

Thanks,
Qian
