### ISSUE TITLE
Unhandled Exception: PlatformException(error, Unsupported value: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 9, 9, 480]., null)

### ISSUE THREAD

**Issue by Saroopashree** [shaqian/flutter_tflite#46]
I'm now trying to use tflite models in flutter apps. The model which I've used is the ssd mobilenet model in your "flutter_realtime_detection" application. Almost all the code that I've done is based on yours. Even then the IllegalArgumentException occurs. I don't know from where the error originates. Please help me out.
[camera.txt](https://github.com/shaqian/flutter_tflite/files/3414962/camera.txt)

**Comment by Saroopashree** [comment]
Hi @shaqian 
Any thoughts on this?

**Comment by shaqian** [comment]
Hi, 

What is the method that you are calling? Is it Tflite.detectObjectOnImage? Can you try if the [example  app](https://github.com/shaqian/flutter_tflite/tree/master/example) works?

Thanks,
Qian

**Comment by shaqian** [comment]
I'm archiving this thread. Feel free to reopen if you have further questions.

Thanks,
Qian

**Comment by mady143** [comment]
Hi @shaqian  @Saroopashree  @laiso  @mgalgs  @prakhar1989 ,

I am new flutter and as well tflite i developed an app to detect the plant disease and when i process a leaf to detect and pass through a tflite model which is converted from hdf5 from python to tflite and i am getting an error 
**Exception has occurred. PlatformException (PlatformException(error, Unsupported value: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 38] and a Java object with shape [1, 40]., null)) in flutter.**

Coulod any one help me
i was totaly confused when i am getting an error can you help me with the solution.

Thanks and Regards
Manikantha Sekhar.
