### ISSUE TITLE
Can't build even from new Flutter project

### ISSUE THREAD

**Issue by ASentimentalMan** [shaqian/flutter_tflite#51]
I've created a brand new Flutter project
Imported tflite dependecy to pubspec.yaml acrroding to README Installation and run "flutter run" after package get to build my flutter app to my iOS Simulator
obviously there were error like "'vector' file not found"
I did what README told to do:

`open ios/Runner.xcworkspace in Xcode, click Runner > Tagets > Runner > Build Settings, search Compile Sources As, change the value to Objective-C++;`

But there are some other errors:

`Failed to build iOS app
Error output from Xcode build:
↳
    2019-08-13 13:15:28.862 xcodebuild[37596:699677]  DTDeviceKit: deviceType from
    00008027-001329AA1498002E was NULL
    2019-08-13 13:15:28.907 xcodebuild[37596:699678]  DTDeviceKit: deviceType from
    00008027-001329AA1498002E was NULL
    ** BUILD FAILED **

Xcode's output:
↳
    warning: The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please
    address deprecated @objc inference warnings, test your code with “Use of deprecated
    Swift 3 @objc inference” logging enabled, and then disable inference by changing the
    "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target. (in target
    'Runner')
    ld: targeted OS version does not support use of thread local variables in
    __ZN14EigenForTFLite15ThreadPoolTemplINS_20StlThreadEnvironmentEE16ScheduleWithHintENSt3
    __18functionIFvvEEEii for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build systemnote: Planning buildnote: Constructing build description`

I googled it and found a result as 

[https://stackoverflow.com/questions/44379348/the-use-of-swift-3-objc-inference-in-swift-4-mode-is-deprecated](url)

After doing that, here was one last error:

Error output from Xcode build:
↳
    2019-08-13 13:27:29.227 xcodebuild[39427:733244]  DTDeviceKit: deviceType from
    00008027-001329AA1498002E was NULL
    2019-08-13 13:27:29.299 xcodebuild[39427:733281]  DTDeviceKit: deviceType from
    00008027-001329AA1498002E was NULL
    ** BUILD FAILED **

`Xcode's output:
↳
    ld: targeted OS version does not support use of thread local variables in
    __ZN14EigenForTFLite15ThreadPoolTemplINS_20StlThreadEnvironmentEE16ScheduleWithHintENSt3
    __18functionIFvvEEEii for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build systemnote: Planning buildnote: Constructing build description`

I can't solve this problem even I tried what I can googled
After that, I tried to run the example in this github Repository directly
But still got errors

I appreciate with your work but it really needs to be update soon

**Comment by shaqian** [comment]
Hi ASentimentalMan,

The last error looks similar to https://stackoverflow.com/questions/52282646/build-error-targeted-os-version-does-not-support-use-of-thread-local-variables
 Can you try changing Deployment target to 9.0 or greater?

Thanks,
Qian

**Comment by shaqian** [comment]
I'm archiving this thread. Feel free to reopen if you have further questions.

Thanks,
Qian
