### ISSUE TITLE
RunModelOnImage causes crash on iOS; Works fine on Android

### ISSUE THREAD

**Issue by lpadgett** [shaqian/flutter_tflite#52]
Hello,

The following is the section of my code which causes a crash for my app on iOS 12.1.2 using an iPhone 6.

Future<List> analyze(String imagePath) async {
    String model = await Tflite.loadModel(
        model: Assets.myModel,
        labels: Assets.myModelLabels,
        numThreads: 1 // defaults to 1
    );
    var analysis = await Tflite.runModelOnImage(
        path: imagePath,
        // required
        imageMean: 0.0,
        // defaults to 117.0
        imageStd: 255.0,
        // defaults to 1.0
        numResults: 1,
        // defaults to 5
        threshold: 0.2,
        // defaults to 0.1
        asynch: true // defaults to true
    );
    return analysis;
  }

loadModel causes no issues. However, when I call runModelOnImage for any picture I take, the app crashes. I went through with a debugger in Android Studio and it does not crash on any of the code I have written, but no feedback is provided when it crashes and everything just stops.

When I repeat this using Xcode to build instead of Android Studio, a breakpoint is automatically created and execution stops on line 65 of ios_image_load.mm. I am confident that I did not do anything to cause this as I did not write the code in that file. The following text is what was displayed by Xcode when I could not progress any further in the application before causing the crash of the app (happening in "LoadImageFromFile(const char* file_name,  int* out_width, int* out_height, int* out_channels" of the ios_image_load.mm file):

2019-08-16 15:46:56.285280-0500 Runner[24458:5125639] flutter: Observatory listening on http://127.0.0.1:57634/8aOsiY60hlQ=/
2019-08-16 15:47:20.297500-0500 Runner[24458:5125630] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-08-16 15:47:20.298693-0500 Runner[24458:5125630] [MC] Reading from public effective user settings.
2019-08-16 15:47:23.866548-0500 Runner[24458:5125538] Could not load IOSurface for time string. Rendering locally instead.
Loaded model 1resolved reporter2019-08-16 15:47:27.824862-0500 Runner[24458:5125538] [Unknown process name] CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
(lldb) 

There are no problems that I have noticed with Android, only iOS.

Here is a screenshot of what I saw in Xcode before the app would crash.
![Screen Shot 2019-08-16 at 3 58 52 PM](https://user-images.githubusercontent.com/20961889/63197948-d248c300-c03e-11e9-9f29-2aefaed4712c.png)

**Comment by shaqian** [comment]
Hi Ipadgett,

I think the error "CGContextDrawImage: invalid context 0x0" is because `CGBitmapContextCreate` failed to create context from the image data. If you are loading a image from your phone, can you try a different image? Or use `runModelOnFrame` to run model camera frame instead?

Thanks,
Qian

**Comment by shaqian** [comment]
I'm archiving this thread. Feel free to reopen if you have further questions.

Thanks,
Qian

**Comment by zoraiz-WOL** [comment]
my app is crashing when tflite.runonmodel calls. please help me in this

CODE:
import 'dart:io';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:leak_detector/leak_detector.dart';
import 'package:tflite/tflite.dart';

class ImageDetect extends StatefulWidget {
  const ImageDetect({Key? key}) : super(key: key);

  @override
  ImageDetectState createState() => ImageDetectState();
}

class ImageDetectState extends State<ImageDetect> {
  File? _image;
  final ImagePicker _picker = ImagePicker();
  bool _loading = false ;
  List<dynamic>? _outputs;

  @override
  void initState() {
    super.initState();
    //_loading = true;
    loadModel();
    LeakDetector().init(maxRetainingPath: 300);
  }
  @override
  void dispose() {
    Tflite.close();

    super.dispose();
  }


  loadModel() async {
    await Tflite.loadModel(
      model: "assets/model.tflite",
      labels: "assets/labels.txt",
    );
    // setState(() {
    //   _loading=false;
    // });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(

      appBar: AppBar(
        title: const Text('Image Classification'),
        backgroundColor: Colors.purple,

      ),
      body: _loading
          ? Container(
        alignment: Alignment.center,
        child: CircularProgressIndicator(),
      )
          : Container(

        width: MediaQuery.of(context).size.width,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _image == null ? Container() : Image.file(File(_image!.path) ,width: 100,
              height: 100,
              fit: BoxFit.fitHeight,),
            SizedBox(
              height: 20,
            ),
            _outputs != null
                ? Text('${_outputs![0]["label"]}',
              style: TextStyle(
                color: Colors.black,
                fontSize: 20.0,
                background: Paint()..color = Colors.white,
              ),
            )
                : Container()
          ],
        ),
      ),

      floatingActionButton: FloatingActionButton(
        onPressed: _optiondialogbox,
        backgroundColor: Colors.purple,
        child: Icon(Icons.image),
      ),
    );
  }

  classifyImage(File image) async {
    try{
      loadModel();
    var output =await Tflite.runModelOnImage(
      path: image!.path,
      numResults: 2,
      threshold: 0.5,
      imageMean: 127.5,
      imageStd: 127.5,
      // asynch: true,
    );
    setState(() {
      _loading = false;
      _outputs = output;
    });}
    catch(e){
      print("Exception"+e.toString());
    }
  }

  Future<void> _optiondialogbox() {
    return showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            backgroundColor: Colors.purple,

            content: SingleChildScrollView(
              child: ListBody(
                children: <Widget>[
                  GestureDetector(
                    child: Text(
                      "Take a Picture",
                      style: TextStyle(color: Colors.white, fontSize: 20.0),
                    ),
                    onTap: openCamera,
                  ),
                  Padding(padding: EdgeInsets.all(10.0)),
                  GestureDetector(
                    child: Text(
                      "Select image ",
                      style: TextStyle(color: Colors.white, fontSize: 20.0),
                    ),
                    onTap: openGallery,
                  )
                ],
              ),
            ),
          );
        });
  }

  Future openCamera() async {
    var image = await _picker.getImage(source: ImageSource.camera);

    setState(() {
      _image = File(image!.path);
    });
    classifyImage(File(image!.path));
  }

  //camera method
  Future openGallery() async {
    Tflite.close();
    var piture = await _picker.getImage(source: ImageSource.gallery);
    setState(() {
      _image = File(piture!.path);
    }

    );
    classifyImage(File(piture!.path));
  }
}
