### ISSUE TITLE
Can i save image with Bounding boxes??

### ISSUE THREAD

**Issue by bgparkloop** [shaqian/flutter_tflite#54]
Hello,

I wonder how to save image with Bounding boxes... BB is a widget (positioned), so I can't convert it to image class and also merge positioned class and image class.

Let me know how to do it ...

Thanks

**Comment by shaqian** [comment]
Hi bgparkloop,

You can try the `RepaintBoundary` widget, although I have not used it with this plugin. 
https://api.flutter.dev/flutter/rendering/RenderRepaintBoundary/toImage.html

Thanks,
Qian

**Comment by shaqian** [comment]
I'm archiving this thread. Feel free to reopen if you have further questions.

Thanks,
Qian
