### ISSUE TITLE
Example app won't build on iOS 

### ISSUE THREAD

**Issue by kenthinson** [shaqian/flutter_tflite#57]
`Launching lib/main.dart on Kent Hinson’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: L2F5C82287
Xcode build done.                                            1.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
 /Users/kent/Desktop/mlTest/flutter_tflite/ios/Classes/TflitePlugin.mm:19:10: fatal error: 'tensorflow/lite/kernels/register.h' file not found
    #include "tensorflow/lite/kernels/register.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.

Error launching application on Kent Hinson’s iPhone.

`

**Comment by shaqian** [comment]
Hi Kent,

Can you check if the tensorflow header files are located in "tensorflow/lite/kernels/register.h"? I know in earlier versions the headers are in "tensorflow/contrib/lite/kernels/register.h". 

You can use `CONTRIB_PATH` to toggle the path. Uncomment `//#define CONTRIB_PATH`:
https://github.com/shaqian/flutter_tflite/blob/master/ios/Classes/TflitePlugin.mm#L1

Thanks,
Qian

**Comment by kenthinson** [comment]
@shaqian That worked thanks. You might consider adding that to the documentation https://github.com/shaqian/flutter_tflite/blob/master/example/README.md. It might confuse others too :) thanks again.
