### ISSUE TITLE
ByteBuffer is not a valid flatbuffer model

### ISSUE THREAD

**Issue by Fethi1** [shaqian/flutter_tflite#63]
i used google colab (tensorflow) to generate a .tflite model 

`E/MethodChannel#tflite(12379): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#tflite(12379): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#tflite(12379): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#tflite(12379): 	at android.app.ActivityThread.main(ActivityThread.java:7000)
E/MethodChannel#tflite(12379): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#tflite(12379): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/MethodChannel#tflite(12379): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
I/flutter (12379): Failed to load model + 2.718281828459045`

**Comment by Fethi1** [comment]
i resolved the isuee in case someone faced the same problem, you need to extract the model as .h5 first then convert it to .tflite  as below 
`model.save('mnist.h5')
converter = tf.lite.TFLiteConverter.from_keras_model_file('mnist.h5')
tflite_model = converter.convert()
open('mnist.tflite', 'wb').write(tflite_model)
`

**Comment by sumitgohil** [comment]
Hi, I already have a .tflite model Downloaded from Somewhere. I am getting the same error, how do I make this .tflite model work. Any help would be greatly appreciated.
