### ISSUE TITLE
which version of tflite is used

### ISSUE THREAD

**Issue by KaggleAlbertaAI** [shaqian/flutter_tflite#64]
When I Run 'flutter pub get' in terminal to compile and prepare components stated in file 'pubspec.yaml', I got error below:
Because tflite_example depends on both tflite from hosted and tflite from path,
version solving failed.
My question is what version of tflite should we state in 'pubspec.yaml'?
I have tried many options like one of them 'tflite: ^1.0.0'.

**Comment by shaqian** [comment]
The example in this repo use tflite from relative path. 
https://github.com/shaqian/flutter_tflite/blob/master/example/pubspec.yaml#L31-L32

In your own project, you can use
either 
```
  tflite:
    path: ../
```
or 
```
  tflite: ^1.0.0
```
but not both. 

Thanks,
Qian

**Comment by shaqian** [comment]
I'm closing the issue for now. Feel free to reopen if you have other questions.

Thanks,
Qian
