### ISSUE TITLE
need tensorflow lite 1.14.0

### ISSUE THREAD

**Issue by maxiloEmmmm** [shaqian/flutter_tflite#65]
ios: TensorFlowLiteObjC (1.14.0) or TensorFlowLiteSwift(1.14.0)

**Comment by shaqian** [comment]
Sorry for the delay. In the new version 1.1.0, TF Lite is upgraded to TensorFlowLiteObjC 2.2.0.

Thanks,
Qian

**Comment by maxiloEmmmm** [comment]
辛苦辛苦
