### ISSUE TITLE
Model doesn't accept image 

### ISSUE THREAD

**Issue by Fethi1** [shaqian/flutter_tflite#66]
this happen whenever i pass an image to the model aka use runmodelonImage 

```
E/MethodChannel#tflite(18441): Failed to handle method call
E/MethodChannel#tflite(18441): java.lang.IllegalArgumentException: Unsupported value: java.lang.RuntimeException: Interpreter busy
E/MethodChannel#tflite(18441): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#tflite(18441): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#tflite(18441): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/MethodChannel#tflite(18441): 	at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:101)

```

**Comment by shaqian** [comment]
Hello,

You will need to select a model before passing a image. Click the menu button on top right.

Thanks,
Qian

**Comment by Fethi1** [comment]
i have loaded a model successfully it is a custom model and i'm using it on a new app not the example app

**Comment by Ehtasha** [comment]
@shaqian  Please reply on custom model issue.

Is it possible to use method ` runSegmentationOnModel ` for out custom model ?

**Comment by Fethi1** [comment]
i'm gonna close this issue because my model takes image byte array as input not the image itself so i converted it to byte array and use `runmodelonbinary` and it works
