### ISSUE TITLE
Tflite failing to close

### ISSUE THREAD

**Issue by MATTYGILO** [shaqian/flutter_tflite#68]
My program gets caught on `await Tflite.close()` as such when i want to load the model again it causes this error

Attempt to invoke virtual method 'boolean java.util.Vector.add(java.lang.Object)' on a null

**Comment by shaqian** [comment]
Hello,

The only `Vector` used in Java code is `labels`. `labels` is set to null in Tflite.close(), but when you load a new model, `loadLabels()` will be called and a new `Vector` is created.

You can set a breakpoint to check if new `Vector` is created correctly.  
https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L225-L228

Thanks,
Qian

**Comment by shaqian** [comment]
Archiving the thread. Feel free to reopen if you have further questions. 

Thanks,
Qian
