### ISSUE TITLE
Example are not building

### ISSUE THREAD

**Issue by adyachok** [shaqian/flutter_tflite#70]
Hi,
I am new guy to Flutter, so maybe I am doing something wrong, however while trying to run example from the project I got next error 

> Launching lib/main.dart on iPhone 8 in debug mode...
Removing obsolete reference to flutter_assets from Runner.app
Xcode build done.                                            3.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/someuser/projects/PUBLIC/flutter_proj/flutter_tflite/ios/Classes/TflitePlugin.mm:19:10: fatal error: 'tensorflow/lite/kernels/register.h' file not found
    #include "tensorflow/lite/kernels/register.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

I tried other projects containing tflite as a dependency and I didn't get such an error.
Also, I tried to change workspace and project build system to legacy, but it didn't help.

**Comment by Statyk7** [comment]
I have the same issue... Any help on this?

**Comment by oldschool1717** [comment]
On Android, I am getting the following when running the example: ByteBuffer is not a valid flatbuffer model (when initially loading the model). Is this a versioning issue perhaps? Thanks.

**Comment by shaqian** [comment]
Hi @adyachok @Statyk7,

Can you check if the tensorflow header files are located in "tensorflow/lite/kernels/register.h"? I know in earlier versions the headers are in "tensorflow/contrib/lite/kernels/register.h".

You can use `CONTRIB_PATH` to toggle the path. Uncomment `//#define CONTRIB_PATH`:
https://github.com/shaqian/flutter_tflite/blob/master/ios/Classes/TflitePlugin.mm#L1

Thanks,
Qian

**Comment by shaqian** [comment]
I'm closing the issue for now. Feel free to reopen if you have other questions.

Thanks,
Qian

**Comment by k1ycee** [comment]
This is not working for me at the moment
