### ISSUE TITLE
调用前置摄像头出现反向的结果

### ISSUE THREAD

**Issue by yangzpgithub** [shaqian/flutter_tflite#73]
你好，这个包很棒，我在学习使用的时候，把他改成了前置摄像头，但姿态估计，也就是posenet这一块出现了左右估计反向的结果，还会测试不准确。是不是前置摄像头无法使用。

**Comment by haorendashu** [comment]
这个问题解决了吗？ @yangzpgithub

**Comment by haorendashu** [comment]
@yangzpgithub 你好，问题有解决吗？
