### ISSUE TITLE
Instead of inputing a photo can you input an array?

### ISSUE THREAD

**Issue by MATTYGILO** [shaqian/flutter_tflite#8]
I was wondering if there is a way of inputing an array into the neural net instead a file path?

**Comment by shaqian** [comment]
Hi MATTYGILO,

Sorry for the delayed response. Unfortuantely it's not supported to input an array at the moment.

The array data is generated from image file at the following line in iOS and Android respectively. 
https://github.com/shaqian/flutter_tflite/blob/master/ios/Classes/TflitePlugin.mm#L166
https://github.com/shaqian/flutter_tflite/blob/master/android/src/main/java/sq/flutter/tflite/TflitePlugin.java#L156

You can try to create a new method call that accepts array directly. I will add this in future version. 

Thanks,
Qian

**Comment by MATTYGILO** [comment]
Thank you allot. I will go about trying what you suggested. Cant wait for the future update it will allow for more differentiation for machine learning on flutter apps.

**Comment by MATTYGILO** [comment]
Just wondering when that update will be ready for. I had a go but i wasn't able to achieve it.

**Comment by shaqian** [comment]
Sorry I'm behind schedule. I will find time this weekend.

**Comment by MATTYGILO** [comment]
Thanks a lot, sorry it took a while to get back to you.

**Comment by shaqian** [comment]
Archiving the issue for now. Feel free to reopen if you have other questions.
