### ISSUE TITLE
build release failed in flutter v1.12.13

### ISSUE THREAD

**Issue by iyuhang** [shaqian/flutter_tflite#86]
Removed unused resources: Binary resource data reduced from 840KB to 797KB: Removed 5%
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':tflite:verifyReleaseResources'.             
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/apple/Flutter/projects/fixtime/build/tflite/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
  /Users/apple/Flutter/projects/fixtime/build/tflite/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 50s                                                  
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     111.6s
Gradle task assembleRelease failed with exit code 1

flutter dcotor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by iyuhang** [comment]
I  add this to build.gradle

subprojects {
    project.evaluationDependsOn(':app')
        afterEvaluate {project ->
            if (project.hasProperty("android")) {
                android {
                    compileSdkVersion 28
                    buildToolsVersion '28.0.3'
                }
                configurations.all {
                    resolutionStrategy { 
                        force 'com.google.android.gms:play-services-gcm:16.1.0'
                        force 'com.google.android.gms:play-services-location:16.0.1'
                        force 'com.google.android.gms:play-services-basement:16.2.0'
                        force 'com.google.android.gms:play-services-auth:16.0.1'
                        force 'com.google.android.gms:play-services-stats:16.0.1'
                        force 'com.google.android.gms:play-services-base:16.0.1'
                    }
                }
            }
        }
    
} 

it reports

FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Could not determine the dependencies of task ':location:compileReleaseAidl'.                                       
> Could not resolve all task dependencies for configuration ':location:releaseCompileClasspath'.                   
   > Could not find com.google.android.gms:play-services-location:16.0.1.                                          
     Required by:                                                                                                  
         project :location                                                                                         
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 2m 53s

**Comment by iyuhang** [comment]
@shaqian 求救呀~~

**Comment by iyuhang** [comment]
原来是插件 compileSdkVersion 是27 ，需要更改到 28

**Comment by shaqian** [comment]
Closing the issue as the PR is merged.
