### ISSUE TITLE
build iOS failed in flutter 1.12.13

### ISSUE THREAD

**Issue by iyuhang** [shaqian/flutter_tflite#87]
While building module 'tflite' imported from /Users/apple/Flutter/projects/fixtime/ios/Runner/GeneratedPluginRegistrant.m:140:
    In file included from <module-includes>:1:
    In file included from /Users/apple/Flutter/projects/fixtime/build/ios/Debug-iphoneos/tflite/tflite.framework/Headers/tflite-umbrella.h:13:
    /Users/apple/Flutter/projects/fixtime/build/ios/Debug-iphoneos/tflite/tflite.framework/Headers/ios_image_load.h:1:10: fatal error: 'vector' file not found
    #include <vector>
             ^~~~~~~~
    1 error generated.
    /Users/apple/Flutter/projects/fixtime/ios/Runner/GeneratedPluginRegistrant.m:140:9: fatal error: could not build module 'tflite'
    #import <tflite/TflitePlugin.h>
     ~~~~~~~^
    84 warnings and 2 errors generated.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by suha-glal** [comment]
I have the same issue

**Comment by iyuhang** [comment]
@suha-glal 

iOS
If you get error like "'vector' file not found", please open ios/Runner.xcworkspace in Xcode, click Runner > Tagets > Runner > Build Settings, search Compile Sources As, change the value to Objective-C++;

**Comment by JoseGeorges8** [comment]
@iyuhang is there any other workarounds for this? please. If I do that then other plugins fail for some reason.
I'm so tired of dealing with dependencies ugh.

**Comment by NighttCoder** [comment]
@iyuhang your suggested workaround causes issues in building other plugins. Would be great if this is fixed properly.
I am currently commenting the contents of ios_image_load.h and instead copy and paste this content into ios_image_load.mm and TflitePlugin.mm inplace of the header file.

This seems to work, but would be great if there is a proper solutiion.

**Comment by marciovalim** [comment]
@NighttCoder saved my day!

**Comment by km9134** [comment]
Anyone get a solution for this? Changing to objective C++ allows it to build but I noticed my camera plugin now doesn't work
