### ISSUE TITLE
custom model recognitions make no sense on IOS

### ISSUE THREAD

**Issue by vervorm** [shaqian/flutter_tflite#89]
Hi,

I implemented a custom model on Android I get correct predictions, but IOS is totally weird and makes no sense.

My model_labels.txt has 10 labels, so label index from 0 to 9.

I use this code when I get my image

>     Future<List<dynamic>> recognizeImage(File image) async {
>      await loadModel();
> 
>     var recognitions = await Tflite.runModelOnImage(
>       path: image.path,
>       imageMean: 0.0, // defaults to 117.0
>       imageStd: 256.0, // defaults to 1.0
>       numResults: 5, // defaults to 5
>       threshold: 0.01, // defaults to 0.1
>       asynch: true,
>     );
> 
>     print(recognitions);
>     return result;}

print of the recognitions return on android (=makes sense)
```
[{confidence: 0.9737526178359985, index: 0, label: label1}, 
{confidence: 0.025052303448319435, index: 6, label: label2}]
```

But on IOS,  I get my prediction, I get label indexes from as high as 35 while max should be 9. 
And I get prediction confidence values back as high as 3.3...????? 

print of the recognitions return on IOS (=nonsense)
```
[{index: 21, label: , confidence: 2.8203511238098145}, 
{index: 11, label: label1, confidence: 2.743105411529541}, 
{index: 17, label: label2, confidence: 2.7106339931488037}, 
{index: 10, label: , confidence: 2.4108083248138428}, 
{index: 28, label: label2, confidence: 2.398569107055664}]
```

What's wrong in this picture:
1. index: 21 and index: 10 have no label, makes sense because there's no label
2. index: 17 and index: 28 have the same label but different confidences, which makes no sense as there should be no multiple predictions with the same label
3. all confidence values are more than 1 again no sense

has anybody experienced the same?

**Comment by vervorm** [comment]
I'm closing this myself with what I found. 
After looking deeper into the result, I saw that after the nonsense results, there were correct results. So I just skip the nonsense results. That's it.
Is this correct? No, but it does the job.

**Comment by MATTYGILO** [comment]
I am having the same issue, can you tell me what you did?

**Comment by MATTYGILO** [comment]
> I'm closing this myself with what I found.
> After looking deeper into the result, I saw that after the nonsense results, there were correct results. So I just skip the nonsense results. That's it.
> Is this correct? No, but it does the job.

Could you please tell me what you did as I’m having the same problem

**Comment by vervorm** [comment]
So like I said above, my model has 10 labels which correspond in the result list with an index from 0 to 9. On IOS when I print out the result list I can get results like this one:

```
[
    {index: 10, label: , confidence: 4.047418117523193}, 
    {index: 1, label: early blight, confidence: 0.5834740400314331}, 
    {index: 9, label: healthy, confidence: 0.20530462265014648}, 
    {index: 4, label: septoria leaf spot, confidence: 0.20461072027683258}
]
```

So I loop through the list and I pop the results where the index is null or bigger than 9.
```

var recognitions = await Tflite.runModelOnImage(
      path: image.path,
      imageMean: 0.0, // defaults to 117.0
      imageStd: 256.0, // defaults to 1.0
      // numResults: 5, // defaults to 5
      // threshold: 0.01, // defaults to 0.1
      asynch: true,
    );
//I create a new result list 
List<dynamic> noNonse = [];
for (var i = 0; i < recognitions.length; i++) {
      bool isNonsense = recognitions[i]['index'] > 9;
      if (!isNonsense) {
        noNonse.add(recognitions[i]);
      }
    }
print(noNonse); //list with correct results
```
That's it.
