### ISSUE TITLE
How to find the mean and deviation for the input?

### ISSUE THREAD

**Issue by Pizza1** [shaqian/flutter_tflite#9]
Hi,

How do you find the mean and deviation for the input?

Thanks

**Comment by shaqian** [comment]
Hi,

It depends on the input normalization required by the model. If you use a pretrained model, you can check how images are prepared to train or test the model.

Thanks,
Qian

**Comment by shaqian** [comment]
Archiving the issue for now. Feel free to reopen if you have other questions.
