### ISSUE TITLE
SSDMobileNetV3 no output at all

### ISSUE THREAD

**Issue by sooxt98** [shaqian/flutter_tflite#90]
This is my model structure
![image](https://user-images.githubusercontent.com/13378059/74107506-df88d980-4bab-11ea-8545-5e73e5d9c18d.png)

It works on tflite official app tho. So the problem should be related to this library
![IMG_7696](https://user-images.githubusercontent.com/13378059/74107530-14952c00-4bac-11ea-878d-2e8a02246428.jpg)

**Comment by ourii** [comment]
Hi @sooxt98 ,
Did you manage to make SSDMobileNetV3 work within Flutter?
Just wanted to confirm.

Thanks!

**Comment by sooxt98** [comment]
@ourii  yes after tons of research and trying, I found out that the inference_type must use FLOAT in order to make it work

**Comment by ourii** [comment]
Good to know @sooxt98 ! And how do you actually change the weights from int to float? I guess the model needs to be trained from the beginning with float weights instead of int weights, right?
But I don't see any parameter for changing this in the .config file... where do you have to specify it?

**Comment by Willert98** [comment]
mabye  img preprocessing  have divce  255?

**Comment by ourii** [comment]
But did you change any configuration when training the model, or after training the model?
I am using RGB images, with values from 0 to 255...

**Comment by ourii** [comment]
Hello,
I finally managed to make it work.

For the record, I used the following:
- Trained ssd_mobilenet_v3_small_coco from the [Tensorflow Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)
- Exported checkpoint to tflite frozen graph (.pb) with the following [link](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_ssd_graph.py)
- Convert .pb to .tflite with the following command:

tflite_convert \
  --graph_def_file=built_graph/ssd_mobilenet_v3.pb \
  --output_file=built_graph/ssd_mobilenet_v3.tflite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape=1,300,300,3 \
  --input_arrays='normalized_input_image_tensor' \
  --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
  --mean_values=0 \
  --std_dev_values=255 \
  --inference_type=FLOAT \
  --input_data_type=FLOAT \
  --allow_custom_ops \
  --add_postprocessing_op=True
