### ISSUE TITLE
TFLITE file predicts differently on phone compared to computer

### ISSUE THREAD

**Issue by MATTYGILO** [shaqian/flutter_tflite#97]
[{index: 490, label: label1, confidence: 164.34951782226562}, {index: 801, label: label2, confidence: 102.44239807128906}, {index: 403, label: label3, confidence: 97.45825958251953}]

Surely confidence should be between 0 and 1

It predicts correctly on my computer when using the tflite file. But not on my phone.

**Comment by MATTYGILO** [comment]
@shaqian can you please suggest what I should do. This is only an issue on IOS, android works normally. This is a custom model just to say.

First issue I only have 400 Indices but the prediction has one at 801
Second issue confidence should be between 0 and 1 but I have some up to 164?????

Do you know of any work arounds or could you fix this thanks.

**Comment by AbdulRashidReshamwala** [comment]
what is your last layer of your network

**Comment by MATTYGILO** [comment]
I can't remember that well but I believe I had to train my neural network so inputs were not in range [0, 1] but in [0, 256].

**Comment by vikas-shrma** [comment]
@MATTYGILO  how to create custom model.
I am using `https://teachablemachine.withgoogle.com/`
or do you have any another platform to create modesl
